graphhopper:
  datareader.file: england-latest.osm.pbf
  graph.location: gh-graph-cache

  # Encoded values needed for per-request dimension restrictions
  graph.encoded_values: max_height, max_width, max_weight, max_length

  profiles:
    - name: pcv
      vehicle: car
      custom_model_files: [pcv.json]

  # Landmarks (not CH) — required to support per-request custom model overrides
  profiles_lm:
    - profile: pcv

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 127.0.0.1
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 127.0.0.1
